# Generated by Django 4.1.4 on 2023-03-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='media/blank-profile-picture.jpg', upload_to='media/profile_images'),
        ),
    ]
