# Generated by Django 4.1.4 on 2023-03-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='blank-profile-picture.jpg', upload_to='media/profile_images'),
        ),
    ]
