# Generated by Django 4.1.4 on 2023-03-24 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postimg',
            field=models.ImageField(default='media/default.png', upload_to='media/post_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
