# Generated by Django 4.1.4 on 2023-03-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postimg',
            field=models.ImageField(default='static/images/resources/profile_default.png', upload_to='media/post_images'),
        ),
    ]
