# Generated by Django 4.1.4 on 2023-03-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_post_postimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postimg',
            field=models.ImageField(default='media/default-profile-icon-24.jpg', upload_to='media/post_images'),
        ),
    ]
