# Generated by Django 4.1.4 on 2023-03-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postvid',
            field=models.ImageField(blank=True, upload_to='media/post_video'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postimg',
            field=models.ImageField(upload_to='media/post_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='media/default-profile-icon-24.jpg', upload_to='media/profile_images'),
        ),
    ]
